\c oss;

INSERT INTO gear (name, price, rating, is_user_submitted, is_expensive, image, link, property_type, description, materials, color, detail1, detail2, manufactured, wear, designed_by) VALUES
('Rank Rashguard' ,59.99, 4.5 ,false, false,'https://bjjfightgear.com/cdn/shop/products/GroundForce_RankedRashguard_01_695x695.png?v=1607945591','https://bjjfightgear.com/products/ground-force-rank-rash-guard','rashguard','Designed for grappling and BJJ','82% Polyester and 18% Spandex','Black','Sublimated graphic','200 GSM','America', 'mens', 'ground force'),
-- ('Black Hawk BJJ', 59.99 , 5, false, false, 'https://wartribegear.com/wp-content/uploads/2021/11/Black-Hawk-Rash-Guard-Front.png', 'https://wartribegear.com/shop/black-hawk-black-bjj-rash-guard-black/', 'rashguard', 'Black Rashguard', '82% Polyester and 18% Spandex','Black', 'Sublimated graphic', '200 GSM', 'America', 'mens', 'war tribe' ),
-- ('Strike Red BJJ', 59.99, 4, false, false, 'https://wartribegear.com/wp-content/uploads/2021/11/Strike-Rash-Guard-Front-600x600.png', 'https://wartribegear.com/shop/strike-bjj-rash-guard/', 'rashguard', 'Strike Red Rashguard', '82% Polyester and 18% Spandex','Black', 'Sublimated graphic', '200 GSM', 'America', 'mens', 'war tribe' ),
-- ('Lord Of War', 59.99, 5, false, false, 'https://wartribegear.com/wp-content/uploads/2021/11/Warlord-Rash-Guard-Front.png', 'https://wartribegear.com/shop/warlord-bjj-rash-guard/', 'rashguard', 'Black Rashguard', '82% Polyester and 18% Spandex','Black', 'Sublimated graphic', '200 GSM', 'America', 'mens', 'war tribe' ),
('Patriot Black Hawk Grappling Shorts', 59.99, 4, false, false, 'https://i.imgur.com/mgTWWLf.png', 'https://wartribegear.com/shop/patriot-black-hawk-shorts-black/', 'shorts', 'Black Grappling Shorts', '82% Polyester and 18% Spandex','Black', 'Sublimated graphic', '200 GSM', 'America', 'mens', 'war tribe' ),
('Patriot Black Hawk Grappling Shorts', 59.99, 4, false, false, 'https://i.imgur.com/rkPwxy4.png', 'https://wartribegear.com/shop/patriot-black-hawk-shorts-gray/', 'shorts', 'Pink Grappling Shorts', '82% Polyester and 18% Spandex','Pink', 'Sublimated graphic', '200 GSM', 'America', 'mens', 'war tribe'),
-- ('Adult Grappling Shorts', 39.99, 5, false, false, 'https://wartribegear.com/wp-content/uploads/2017/12/Basic-Shorts-2-Shorts-Front-1.png', 'https://wartribegear.com/shop/grappling-short-comp-standard-black/', 'shorts', 'Black Grappling Shorts', '82% Polyester and 18% Spandex','Black', 'Sublimated graphic', '200 GSM', 'America', 'mens', 'war tribe'),
('Blossom Rashguard', 59.95, 4, false, false, 'https://i.imgur.com/69AKxXF.png','https://fujisports.com/collections/womens-jiu-jitsu-rashguards/products/womens-blossom-rashguard-black-pink', 'rashguard', 'Cherry Blossom Rashguard', '88% Polyester 12% Spandex', 'Black', 'Antimicrobial', 'Fully Sublimated', 'America' , 'womens', 'fuji'),
('Blossom Rashguard', 59.95, 4, false, false, 'https://fujisports.com/cdn/shop/products/Artboard1_8ea9c181-4621-45a5-81b0-8343c7471de9_1600x1600.jpg?v=1668736405','https://fujisports.com/collections/womens-jiu-jitsu-rashguards/products/womens-blossom-rashguard-blue-pink', 'rashguard', 'Cherry Blossom Rashguard', '88% Polyester 12% Spandex', 'Blue', 'Antimicrobial', 'Fully Sublimated', 'America', 'womens', 'fuji'),
('Equilbrium Gi', 169.99, 5, false, true, 'https://i.imgur.com/MBHbMYU.png', 'https://wartribegear.com/shop/womens-equilibrium-jiu-jitsu-gi/','gi', 'Black Equilibrium Gi', 'Pearl Weave', 'Black', '10 Ounce Rip-Stop Pants', '350 GSM Pearl Weave Jacket', 'America', 'womens', 'war tribe'),
('Evolve', 54.99, 4, false, false, 'https://i.imgur.com/51RgBZO.png', 'https://wartribegear.com/shop/evolve-belt-rank-rash-guards/', 'rashguard', 'White Evolve Rashguard', 'High Quality 90/10 Polyester and Lycra Blend', 'White', 'Sublimated graphics that will not peel or rub off', 'Stretch-fit fabric, form fitting', 'America', 'mens', 'war tribe'),
('Standard Short Sleeve', 55.00, 5, false, false, 'https://i.imgur.com/teM4PMr.png', 'https://fujisports.com/collections/renzo-gracie-store/products/renzo-gracie-standard-short-sleeve-rashguard-black', 'rashguard', 'Black Standard Renzo Rashguard', 'Anti-microbial fabric', 'Black', 'Reinforced stiching', 'IBJJF approved for No-Gi competition', 'Japan', 'mens', 'renzo gracie'),
('Replacement Gi Pants Belt', 8.95, 5, false, false, 'https://cdn11.bigcommerce.com/s-74e08ai/images/stencil/1000x1000/products/437/2155/Belt1__82728.1593240389.jpg?c=2', 'https://originmaine.com/bjj-mma-fit/bjj-gis/replacement-gi-pants-belt/', 'belts', 'Replacement Gi Pants Belt', 'Rope', 'Black', 'Swivel-loc', 'Easy clip belt', 'America', 'misc', 'origin'),
('Flow Tech Gi', 149.95, 4 , false , false , 'https://i.imgur.com/Wno5VoL.png', 'https://jitsuarmor.com/products/womens-flow-tech-bjj-gi', 'gi', ' FlowTech', ' Extra Lightweight 350g Pearl Weave Gi Jacket', ' White', ' Triple Reinforced Rip Stop Pants', 'Stiff collar with extra rows of stitching ', 'Japan ', 'womens', 'fuji'),
('Matrix Lime Zest', 149.00, 5, false, true, 'https://cdn.shopify.com/s/files/1/0224/6724/8200/products/gloves-muay-thai-yokkao-matrix-lime-zest-3_1024x1024.jpg?v=1631283104', 'https://yokkao.com/collections/muay-thai-gloves/products/matrix-lime-zest-boxing-gloves?variant=40246139617475', 'gloves', 'Black Embroidered YAKKAO Logo', '100% Genuine Cowhide Leather', 'Green', 'Double-stitched Seams for Reinforced Durability', 'Hook-and-loop Closure', 'Thailand', 'misc', 'yokkao'),
('Tatami Gentle Panda', 60, 4.5, false, false, 'https://i.imgur.com/5cuqYzv.jpeg', 'https://bjjfightgear.com/collections/all-rashguards/products/tatami-gentle-panda-rashguard', 'rashguard', 'Designed by Chris Burns', 'Polyester-spandex fabric blend', 'Black', 'Moisture wicking material', 'Durable and comfortable ', 'America', 'mens', 'bjj fightwear'),
('Competition Gi',185,5,FALSE,FALSE,'https://fujisports.com/cdn/shop/products/Renzo_Gracie_Comp_Gi__0002_download_7_1600x1600.jpg?v=1571722305', 'https://fujisports.com/collections/renzo-gracie-store/products/renzo-gracie-adult-2018-competition-gi','gi','Designed by Renzo Gracie','FUJI Premium Cotton Blend', 'White', 'Super Lightweight', 'Special Reinforcements', 'America', 'mens','renzo gracie'),
('Competition Gi',185,5,FALSE,FALSE,'https://fujisports.com/cdn/shop/products/RENZO_GI_0001_renzogi2_1600x1600.jpg?v=1571722305', 'https://fujisports.com/collections/renzo-gracie-store/products/renzo-gracie-adult-2018-competition-gi','gi','Designed by Renzo Gracie','FUJI Premium Cotton Blend', 'Blue', 'Super Lightweight', 'Special Reinforcements', 'America', 'mens','renzo gracie'),
('Flames', 69.00, 5, false, false, 'https://cdn.shopify.com/s/files/1/0224/6724/8200/products/Shirt_Flame_ColorwayACopy2_0copy_1200x.jpg?v=1675179124', 'https://yokkao.com/collections/compression-rashguards/products/flames-compression-rashguard', 'rashguard', '"Catch eye" Design', '80% Polyester 20% Elastane super stretch satin Gr 240 Mtq', 'Yellow', 'Reinforced seams with cover technique', 'Silicone tape within the inner seam of garment for greater adherence to the body during movement', 'Italy', 'mens', 'yokkao'),
('Baseline Ranked',60,5,FALSE,FALSE,'https://i.imgur.com/T7V3G1i.jpeg', 'https://bjjfightgear.com/collections/all-rashguards/products/fuji-baseline-ranked-rashguard','rashguard','FUJI Baseline Design','80% Polyester 20% Elastane', 'White', 'Elegant Design', 'Fully Sublimated', 'America', 'mens','fuji'),
('GR ADCC 2022 Short Sleeve',130,5,FALSE,TRUE,'https://i.imgur.com/93vevHg.jpeg', 'https://bjjfightgear.com/collections/all-rashguards/products/future-kimonos-gordon-ryan-adcc-2022-short-sleeve-rash-guard','rashguard','Gordon Ryan ADCC 2022 Style Rashguard','Silk', 'white', 'Future Kimonos ADCC Line', 'Fully Sublimated', 'America', 'mens','future kimonos'),
('Cosmic Long Sleeve',120,5,FALSE,TRUE,'https://i.imgur.com/d7G3BzU.png', 'https://futurekimonos.com/products/cosmic-ranked-series-grey-long-sleeve-rash-guard','rashguard','Ranked Series','Premium Grade Fabric', 'gray', 'Nano-silver Coated', ' Grappling-Specific Smoothseam', 'America', 'mens','future kimonos'),
('Cobra 2099',130,5,FALSE,TRUE,'https://i.imgur.com/mAwPrcM.png', 'https://futurekimonos.com/products/cobra-2099-womens-long-sleeve-rash-guard','rashguard','Sleek Design','Premium Grade Fabric', 'black', 'Nano-silver Coated', ' Grappling-Specific Smoothseam', 'America', 'womens', 'future kimonos'),
('Grey Skull',130,5,FALSE,TRUE,'https://i.imgur.com/A9UBLdg.png', 'https://futurekimonos.com/collections/womens/products/grey-skull-womens-short-sleeve-rash-guard','rashguard','Striking Piece','Premium Grade Fabric', 'black', 'Nano-silver Coated', ' Grappling-Specific Smoothseam', 'America', 'womens', 'future kimonos'),
('YOSO Earth Long Sleeve',130,5,FALSE,TRUE,'https://i.imgur.com/MnqQMJc.png', 'https://futurekimonos.com/collections/womens/products/yoso-earth-womens-long-sleeve-rash-guard','rashguard','YOSO Series','Premium Grade MATTE Fabric', 'black', 'Nano-silver Coated', ' Grappling-Specific Smoothseam', 'America', 'womens', 'future kimonos'),
('PROTOTYE Grey Short Sleeve',130,5,FALSE,TRUE,'https://i.imgur.com/tpPjuLO.png', 'https://futurekimonos.com/collections/womens/products/prototype-series-grey-womens-short-sleeve-rash-guard','rashguard','PROTOTYPE Series','Premium Grade Fabric', 'white', 'Nano-silver Coated', ' Grappling-Specific Smoothseam', 'America', 'womens', 'future kimonos');
-- ('NAME',333,5,FALSE,FALSE,'www.image.link', 'www.link.link','rashguard','Pretty','Silk', 'COLOR', 'DETAIL1', 'DETAIL2', 'MANUFACTURED', 'MENS','DESIGNED_BY');


INSERT INTO users (username, password, email, profileImg, address, zipcode, rating, customerType, admin, joinedDate) VALUES 
('test1', 'test1', 'test1@test.com', 'https://i.imgur.com/8puTSd9.png', '1 test rd', 11111, 3, 'member', false, NOW()),
('test2', 'test2', 'test2@test.com', 'https://i.imgur.com/MmLQSDV.png', '2 test rd', 22222, 1,'member', false, NOW()),
('test3', 'test3', 'test3@test.com', 'https://i.imgur.com/ZlrcYvd.png', '3 test rd', 33333, 5, 'member', true, NOW());

INSERT INTO designer (name, bio) VALUES 
('Origin', 'ORIGIN brand, headquartered in Farmington, Maine, was created by BJJWeekly, & co-creator Pete Roberts back in 2009. Pete''s vision was not to create a "fight brand" but instead a BJJ lifestyle brand that spoke directly to the needs of the everyday BJJ enthusuast. As a designer adn entrepreneur, Pete brings 15+ years of branding experience into an industry which he is passionate about growing.'),
('FUJI', 'FUJI Sports (together with Hatashita Sports) was founded in 1969 by Frank Hatashita, 8th Dan. Hatashita Sensei was Vice-President of the IJF (International Judo Federation), and President of the Pan American Judo Federation, among other positions including an IJF referee, and owner of many dojo and affiliates.'),
('War Tribe', 'War Tribe was established to create innovative products made with high-quality materials for the Jiu Jitsu and mixed martial arts (MMA) athlete. We love Jiu Jitsu, we love MMA, and we love participating in the culture and industry we are a part of. What we do is a result of our passion for the art, sport, and lifestyle of the athletes we serve. Every Jiu Jitsu Gi we design is a direct result of our motto and passion. Made with quality materials and built for the athlete, a War Tribe BJJ Gi is always recognizable on the mat. Complete with unique artistic design, our products have become a statement of defiance, but also of benevolence. Our vast artistic Jiu Jitsu Gi collections reflect the true message of our sport.
The War Tribe mission is to elevate the sport and lifestyle of mixed martial arts through our innovative products while promoting the Jiu Jitsu way of life. One who wears War Tribe is born to win, determination is in their blood and inevitable success is in their future.'),
('B-TEAM', 'B-TEAM, comprised of ex DDS (Danahar Death Squad) Members like "Craig Jones", "Nicky Ryan", "Ethan Crelinsten, and "Nicky Rod" bring a different comedic aspect to Jiu Jitsu apparel. Founded in 2022'),
('Gold', 'To Be Filled...'),
('VHTS', 'To Be Filled...'),
('Half Sumo', 'To Be Filled...'),
('93brand', 'To Be Filled...'),
('Virus', 'To Be Filled...'),
('Sanabul', 'To Be Filled...'),
('Jiujiterio', 'To Be Filled...'),
('Venum', 'To Be Filled...'),
('Hayabusa', 'To Be Filled...'),
('Optimal Human', 'To Be Filled...'),
('Rolljunkie', 'To Be Filled...'),
('Raven', 'To Be Filled...'),
('Scramble', 'To Be Filled...'),
('Xmartial', 'To Be Filled...'),
('Fusion Fight Gear', 'To Be Filled...'),
('Tatami', 'To Be Filled...'),
('MA1', 'To Be Filled...'),
('MOYA', 'To Be Filled...'),
('Phalanx', 'To Be Filled...');